// ============================================================
// CATÁLOGO OFICIAL DOS 44 INDICADORES — matriz_indicadores_renapsi_definitiva_44.xlsx
// ============================================================
// Gerado a partir da aba "Matriz Padronizada" da planilha oficial, preservando
// integralmente sua terminologia (não é lida em tempo de execução pelo navegador —
// os 44 registros abaixo são a transcrição estática e versionada da fonte oficial).
// Não reinserir ISAA, ISRL, ISMP, ISEG (eliminados por duplicidade — ver 'Histórico de Revisão').

export type Periodicidade = 'Semestral' | 'Anual' | 'Mensal';
export type Operador = '>=' | '<=' | '>' | '<' | 'comparativo' | 'nenhum';

export interface IndicatorCatalogEntry {
  sigla: string;
  nome: string;
  dimensao: string;
  publicoOuFonte: string;
  resultadoEsperado: string;
  definicaoOperacional: string;
  formula: string;
  meta: string;
  operador: Operador;
  unidade: string;
  periodicidade: Periodicidade;
  motorCalculo: string;
}

export const INDICATOR_CATALOG: IndicatorCatalogEntry[] = [
  {
    sigla: 'ISA',
    nome: 'Satisfação Geral do Aprendiz',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Experiência global positiva do aprendiz no Programa',
    definicaoOperacional: 'Percentual de aprendizes ativos que avaliam a experiência geral da aprendizagem como Satisfeito ou Muito Satisfeito.',
    formula: '(Respostas Q21 = 4 ou 5 ÷ respostas válidas Q21) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IQPF',
    nome: 'Qualidade Pedagógica da Formação',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Formação teórica com qualidade pedagógica',
    definicaoOperacional: 'Mede a percepção favorável sobre a didática dos professores e a qualidade dos conteúdos ministrados.',
    formula: '(Respostas favoráveis [4 ou 5] em Q8+Q9 ÷ total de respostas válidas em Q8+Q9) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IQRA',
    nome: 'Qualidade dos Recursos de Aprendizagem',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Recursos de aprendizagem avaliados positivamente',
    definicaoOperacional: 'Mede a avaliação favorável dos recursos de aprendizagem: material didático, conteúdo EAD/online/virtual e conforto do polo presencial. Em Q11 e Q12, respostas 0 funcionam como crivo de não aplicabilidade e ficam fora do denominador; em Q10, a resposta 0 permanece válida e não favorável.',
    formula: '(Respostas favoráveis [4 ou 5] em Q10+Q11+Q12 ÷ respostas válidas e aplicáveis em Q10+Q11+Q12) × 100; excluir Q11=0 e Q12=0 do denominador',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IAPE',
    nome: 'Acesso à Plataforma EAD',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Acesso estável ao conteúdo da plataforma EAD',
    definicaoOperacional: 'Percentual de aprendizes que declaram sempre conseguir acessar o conteúdo na plataforma EAD. Como todos recebem login e senha, considerar todas as respostas válidas de Q13.',
    formula: '(Q13 = 3 \'Sempre consigo acessar\' ÷ total de respostas válidas Q13) × 100',
    meta: '≥ 90%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IAR',
    nome: 'Qualidade do Atendimento RENAPSI — Aprendiz',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Atendimento da RENAPSI avaliado positivamente pelos aprendizes',
    definicaoOperacional: 'Percentual de aprendizes que utilizaram o atendimento da RENAPSI e o avaliaram positivamente.',
    formula: '(Q15 = 4 ou 5 ÷ respostas válidas Q15, excluindo Q15=0 \'Nunca precisei falar com a RENAPSI\') × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IAF',
    nome: 'Acolhimento na Formação',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Ambiente formativo acolhedor',
    definicaoOperacional: 'Percentual de aprendizes que concordam ou concordam totalmente que foram tratados com educação, respeito e acolhimento por colegas e professores.',
    formula: '(Q16 = 4 ou 5 ÷ respostas válidas Q16) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IAP',
    nome: 'Acolhimento na Atividade Prática',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Ambiente de prática acolhedor',
    definicaoOperacional: 'Percentual de aprendizes que concordam ou concordam totalmente que foram tratados com educação, respeito e acolhimento no órgão/unidade/setor de trabalho.',
    formula: '(Q17 = 4 ou 5 ÷ respostas válidas Q17) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'INO',
    nome: 'Não Ociosidade na Atividade Prática',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Baixa percepção de ociosidade na prática',
    definicaoOperacional: 'Percentual de aprendizes que discordam ou discordam totalmente da afirmação de que ficam ociosos por muito tempo no local de trabalho.',
    formula: '(Q18 = 1 ou 2 ÷ respostas válidas Q18) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IEA',
    nome: 'Expectativa de Empregabilidade do Aprendiz',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Elevada expectativa de empregabilidade',
    definicaoOperacional: 'Percentual de aprendizes que concordam ou concordam totalmente que terão boas chances de conseguir emprego após o contrato de aprendizagem.',
    formula: '(Q19 = 4 ou 5 ÷ respostas válidas Q19) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IAFA',
    nome: 'Apoio Familiar à Aprendizagem',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Aprendiz Ativo',
    resultadoEsperado: 'Forte incentivo familiar à participação no Programa',
    definicaoOperacional: 'Percentual de aprendizes que informam que a família incentiva muito sua participação no Programa.',
    formula: '(Q20 = categoria de maior incentivo ÷ respostas válidas Q20) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'activeLearnerIndicators.js',
  },
  {
    sigla: 'IDAP',
    nome: 'Desempenho do Aprendiz na Prática',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Mentor da Prática',
    resultadoEsperado: 'Bom desempenho dos aprendizes na prática profissional',
    definicaoOperacional: 'Mede a avaliação favorável dos mentores sobre assiduidade/pontualidade, postura, interesse/iniciativa e capacidade de assimilar e aplicar orientações.',
    formula: '(Respostas favoráveis [4 ou 5] em Q7+Q8+Q9+Q10 ÷ respostas válidas em Q7+Q8+Q9+Q10) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'mentorIndicators.js',
  },
  {
    sigla: 'ICDP',
    nome: 'Contribuição da Prática para o Desenvolvimento',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Mentor da Prática',
    resultadoEsperado: 'Prática profissional contribui para o desenvolvimento do jovem',
    definicaoOperacional: 'Mede a percepção dos mentores sobre a contribuição da atividade prática para melhoria de postura, comunicação e pontualidade.',
    formula: '(Respostas favoráveis [4 ou 5] em Q11+Q12+Q13 ÷ respostas válidas em Q11+Q12+Q13) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'mentorIndicators.js',
  },
  {
    sigla: 'IIFM',
    nome: 'Impacto Financeiro Percebido pelo Mentor',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Mentor da Prática',
    resultadoEsperado: 'Percepção positiva de impacto financeiro',
    definicaoOperacional: 'Percentual de mentores que concordam ou concordam totalmente que a atividade prática contribui para melhorar as condições financeiras do jovem e de sua família.',
    formula: '(Q14 = 4 ou 5 ÷ respostas válidas Q14) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'mentorIndicators.js',
  },
  {
    sigla: 'IAM',
    nome: 'Qualidade do Atendimento do Programa — Mentor',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Mentor da Prática',
    resultadoEsperado: 'Atendimento do Programa avaliado positivamente pelos mentores',
    definicaoOperacional: 'Percentual de mentores que utilizaram os canais de atendimento e os avaliaram favoravelmente, excluindo respostas de não aplicabilidade.',
    formula: '(Respostas favoráveis da escala vigente ÷ respostas válidas Q15, excluindo \'não se aplica/nunca precisou\') × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'mentorIndicators.js',
  },
  {
    sigla: 'IAGD',
    nome: 'Avaliação Geral do Desempenho',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Mentor da Prática',
    resultadoEsperado: 'Desempenho geral dos aprendizes avaliado positivamente',
    definicaoOperacional: 'Percentual de mentores que avaliam favoravelmente, de modo geral, o desempenho dos aprendizes sob sua supervisão.',
    formula: '(Respostas favoráveis da escala vigente em Q16 ÷ respostas válidas Q16) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'mentorIndicators.js',
  },
  {
    sigla: 'IRNA',
    nome: 'Disposição para Receber Novos Aprendizes',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Mentor da Prática',
    resultadoEsperado: 'Locais de prática dispostos a receber novos aprendizes',
    definicaoOperacional: 'Percentual de mentores que provavelmente receberiam ou com certeza continuariam a receber novos aprendizes.',
    formula: '(Q17 = 4 ou 5 ÷ respostas válidas Q17) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'mentorIndicators.js',
  },
  {
    sigla: 'IDF',
    nome: 'Desenvolvimento SocioComportamental Percebido pela Família',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Responsável Legal',
    resultadoEsperado: 'Famílias percebem desenvolvimento sociocomportamental do aprendiz',
    definicaoOperacional: 'Mede a percepção favorável dos responsáveis sobre melhora de postura, comunicação e pontualidade após a entrada do jovem no Programa.',
    formula: '(Respostas favoráveis [4 ou 5] em Q6+Q7+Q8 ÷ respostas válidas em Q6+Q7+Q8) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'guardianIndicators.js',
  },
  {
    sigla: 'IEFR',
    nome: 'Expectativa Familiar de Empregabilidade',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Responsável Legal',
    resultadoEsperado: 'Famílias percebem boas perspectivas de emprego',
    definicaoOperacional: 'Percentual de responsáveis que concordam ou concordam totalmente que o aprendiz terá boas chances de conseguir emprego após o contrato.',
    formula: '(Q9 = 4 ou 5 ÷ respostas válidas Q9) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'guardianIndicators.js',
  },
  {
    sigla: 'IIFR',
    nome: 'Impacto Financeiro Percebido pela Família',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Responsável Legal',
    resultadoEsperado: 'Famílias percebem melhoria financeira',
    definicaoOperacional: 'Percentual de responsáveis que informam que a condição financeira familiar melhorou ou melhorou muito após a entrada do jovem no Programa.',
    formula: '(Q10 = 4 ou 5 ÷ respostas válidas Q10) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'guardianIndicators.js',
  },
  {
    sigla: 'IARR',
    nome: 'Qualidade do Atendimento RENAPSI — Responsável',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Responsável Legal',
    resultadoEsperado: 'Atendimento da RENAPSI avaliado positivamente pelos responsáveis',
    definicaoOperacional: 'Percentual de responsáveis que utilizaram o atendimento da RENAPSI e o avaliaram positivamente.',
    formula: '(Q11 = 4 ou 5 ÷ respostas válidas Q11, excluindo Q11=0 \'Nunca precisei falar com a RENAPSI\') × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'guardianIndicators.js',
  },
  {
    sigla: 'ISR',
    nome: 'Satisfação Geral do Responsável',
    dimensao: 'Pesquisas de Satisfação',
    publicoOuFonte: 'Responsável Legal',
    resultadoEsperado: 'Experiência da aprendizagem avaliada positivamente pelos responsáveis',
    definicaoOperacional: 'Percentual de responsáveis que avaliam a experiência da aprendizagem como Satisfeito ou Muito Satisfeito.',
    formula: '(Q12 = 4 ou 5 ÷ respostas válidas Q12) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Semestral',
    motorCalculo: 'guardianIndicators.js',
  },
  {
    sigla: 'TIP',
    nome: 'Taxa de Inserção Produtiva Pós-Programa',
    dimensao: 'Avaliação Pós-Programa',
    publicoOuFonte: 'Egresso',
    resultadoEsperado: 'Egressos inseridos produtivamente após o Programa',
    definicaoOperacional: 'Percentual de egressos que estão efetivados no mesmo local, empregados formalmente em outra organização ou trabalhando por conta própria.',
    formula: '(Q5 = opções 1, 2 ou 3 ÷ respostas válidas Q5) × 100',
    meta: '≥ 60%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Anual',
    motorCalculo: 'graduateIndicators.js',
  },
  {
    sigla: 'TCE',
    nome: 'Taxa de Continuidade Educacional',
    dimensao: 'Avaliação Pós-Programa',
    publicoOuFonte: 'Egresso',
    resultadoEsperado: 'Egressos mantendo trajetória educacional',
    definicaoOperacional: 'Percentual de egressos que estão cursando Ensino Médio, Ensino Técnico/Profissionalizante ou Ensino Superior.',
    formula: '(Q7 = opções 1, 3 ou 4 ÷ respostas válidas Q7) × 100',
    meta: '≥ 60%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Anual',
    motorCalculo: 'graduateIndicators.js',
  },
  {
    sigla: 'TFET',
    nome: 'Taxa Fora de Estudo e Trabalho',
    dimensao: 'Avaliação Pós-Programa',
    publicoOuFonte: 'Egresso',
    resultadoEsperado: 'Redução de egressos fora de estudo e trabalho',
    definicaoOperacional: 'Percentual de egressos que não estão estudando nem trabalhando, independentemente de estarem ou não procurando emprego.',
    formula: '(Q5 = opções 6 ou 7 ÷ respostas válidas Q5) × 100',
    meta: '≤ 30%',
    operador: '<=',
    unidade: 'Percentual',
    periodicidade: 'Anual',
    motorCalculo: 'graduateIndicators.js',
  },
  {
    sigla: 'IAAP',
    nome: 'Aderência da Situação Atual à Aprendizagem',
    dimensao: 'Avaliação Pós-Programa',
    publicoOuFonte: 'Egresso',
    resultadoEsperado: 'Situação atual relacionada à experiência de aprendizagem',
    definicaoOperacional: 'Percentual de egressos que declaram que sua situação atual tem certa ou muita relação com a experiência de aprendizagem.',
    formula: '(Q6 = opções 3 ou 4 ÷ respostas válidas Q6) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Anual',
    motorCalculo: 'graduateIndicators.js',
  },
  {
    sigla: 'IDSE',
    nome: 'Desenvolvimento SocioComportamental do Egresso',
    dimensao: 'Avaliação Pós-Programa',
    publicoOuFonte: 'Egresso',
    resultadoEsperado: 'Egressos percebem desenvolvimento sociocomportamental',
    definicaoOperacional: 'Mede a percepção favorável do egresso sobre melhoria de postura, comunicação e pontualidade após a experiência como aprendiz.',
    formula: '(Respostas favoráveis [4 ou 5] em Q8+Q9+Q10 ÷ respostas válidas em Q8+Q9+Q10) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Anual',
    motorCalculo: 'graduateIndicators.js',
  },
  {
    sigla: 'IIFE',
    nome: 'Impacto Financeiro Percebido pelo Egresso',
    dimensao: 'Avaliação Pós-Programa',
    publicoOuFonte: 'Egresso',
    resultadoEsperado: 'Egressos percebem melhoria da condição financeira',
    definicaoOperacional: 'Percentual de egressos que informam melhora ou muita melhora na condição financeira própria e de sua família.',
    formula: '(Q11 = 4 ou 5 ÷ respostas válidas Q11) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Anual',
    motorCalculo: 'graduateIndicators.js',
  },
  {
    sigla: 'IAFE',
    nome: 'Apoio Familiar durante o Programa',
    dimensao: 'Avaliação Pós-Programa',
    publicoOuFonte: 'Egresso',
    resultadoEsperado: 'Famílias apoiaram a participação do egresso',
    definicaoOperacional: 'Percentual de egressos que informam que a família incentivou muito sua participação no Programa.',
    formula: '(Q12 = categoria de maior incentivo ÷ respostas válidas Q12) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Anual',
    motorCalculo: 'graduateIndicators.js',
  },
  {
    sigla: 'IIPT',
    nome: 'Importância do Programa para a Trajetória',
    dimensao: 'Avaliação Pós-Programa',
    publicoOuFonte: 'Egresso',
    resultadoEsperado: 'Programa reconhecido como importante para a trajetória do egresso',
    definicaoOperacional: 'Percentual de egressos que atribuem muita ou muitíssima importância ao Programa para sua trajetória.',
    formula: '(Q13 = 4 ou 5 ÷ respostas válidas Q13) × 100',
    meta: '≥ 80%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Anual',
    motorCalculo: 'graduateIndicators.js',
  },
  {
    sigla: 'ATDS',
    nome: 'Análise Transversal — Desenvolvimento Sociocomportamental',
    dimensao: 'Análises Transversais',
    publicoOuFonte: 'Comparação entre públicos',
    resultadoEsperado: 'Convergência positiva sobre desenvolvimento sociocomportamental',
    definicaoOperacional: 'Compara, sem produzir média única, as taxas favoráveis de postura, comunicação e pontualidade percebidas por egresso, responsável e mentor.',
    formula: 'Apresentar lado a lado as taxas favoráveis correspondentes de Egresso, Responsável e Mentor; não calcular média entre públicos.',
    meta: '≥ 80% em cada público/dimensão',
    operador: 'comparativo',
    unidade: 'Comparativo',
    periodicidade: 'Semestral',
    motorCalculo: 'transversalAnalyses.js (TRANSV_DESENVOLVIMENTO_SOCIOCOMPORTAMENTAL)',
  },
  {
    sigla: 'ATIF',
    nome: 'Análise Transversal — Impacto Financeiro Percebido',
    dimensao: 'Análises Transversais',
    publicoOuFonte: 'Comparação entre públicos',
    resultadoEsperado: 'Convergência positiva sobre impacto econômico do Programa',
    definicaoOperacional: 'Compara separadamente a percepção de impacto financeiro entre egresso, responsável e mentor.',
    formula: 'Comparar IIFE × IIFR × IIFM; não calcular média única entre públicos.',
    meta: '≥ 80% em cada público',
    operador: 'comparativo',
    unidade: 'Comparativo',
    periodicidade: 'Semestral',
    motorCalculo: 'transversalAnalyses.js (TRANSV_IMPACTO_FINANCEIRO)',
  },
  {
    sigla: 'ATER',
    nome: 'Análise Transversal — Expectativa e Resultado de Empregabilidade',
    dimensao: 'Análises Transversais',
    publicoOuFonte: 'Comparação entre públicos',
    resultadoEsperado: 'Coerência entre expectativa de emprego e resultados pós-programa',
    definicaoOperacional: 'Compara as expectativas de empregabilidade do aprendiz e do responsável com os resultados observados entre egressos.',
    formula: 'Comparar IEA e IEFR com TIP; sem consolidar em média única.',
    meta: 'IEA ≥ 80%; IEFR ≥ 80%; TIP ≥ 60%',
    operador: 'comparativo',
    unidade: 'Comparativo',
    periodicidade: 'Semestral',
    motorCalculo: 'transversalAnalyses.js (TRANSV_EXPECTATIVA_RESULTADO_EMPREGABILIDADE)',
  },
  {
    sigla: 'ATQA',
    nome: 'Análise Transversal — Qualidade do Atendimento',
    dimensao: 'Análises Transversais',
    publicoOuFonte: 'Comparação entre públicos',
    resultadoEsperado: 'Atendimento do Programa avaliado positivamente pelos diferentes públicos',
    definicaoOperacional: 'Compara a taxa de avaliação favorável do atendimento entre aprendiz, responsável e mentor, sempre excluindo respostas de não aplicabilidade.',
    formula: 'Comparar IAR × IARR × IAM; não calcular média única entre públicos.',
    meta: '≥ 80% em cada público',
    operador: 'comparativo',
    unidade: 'Comparativo',
    periodicidade: 'Semestral',
    motorCalculo: 'transversalAnalyses.js (TRANSV_QUALIDADE_ATENDIMENTO)',
  },
  {
    sigla: 'QAA',
    nome: 'Quantidade de Aprendizes Ativos',
    dimensao: 'Execução do Programa',
    publicoOuFonte: 'Operação e cobertura',
    resultadoEsperado: 'Manter o quantitativo pactuado de adolescentes e jovens no Programa',
    definicaoOperacional: 'Número de aprendizes com contrato ativo no período;',
    formula: 'Número de aprendizes com contrato ativo no mês = data_base.',
    meta: '5000',
    operador: 'nenhum',
    unidade: 'Quantidade',
    periodicidade: 'Mensal',
    motorCalculo: 'indicadoresExecucaoService.js (calcularQAA)',
  },
  {
    sigla: 'PVP',
    nome: 'Percentual de Vagas Preenchidas',
    dimensao: 'Execução do Programa',
    publicoOuFonte: 'Operação e cobertura',
    resultadoEsperado: 'Manter preenchidas pelo menos 95% das 5.000 vagas permanentemente disponibilizadas no Programa.',
    definicaoOperacional: 'Percentual das 5.000 vagas permanentes do Programa ocupadas por aprendizes com contrato ativo na data-base de fechamento (último dia) da competência mensal. Não usar a soma de jovens que passaram pelo Programa no mês.',
    formula: 'PVP = (nº de aprendizes com contrato ativo no último dia da competência ÷ 5.000) × 100',
    meta: '≥ 95%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'indicadoresExecucaoService.js (calcularPVPeTRV)',
  },
  {
    sigla: 'IFM',
    nome: 'Índice de Frequência Mensal nas Atividades Teóricas e Práticas',
    dimensao: 'Execução do Programa',
    publicoOuFonte: 'Operação e cobertura',
    resultadoEsperado: 'Garantir participação regular nas atividades práticas e teóricas',
    definicaoOperacional: 'Percentual de presenças registradas em relação ao total de atividades previstas no período',
    formula: '(Ʃ freq_util ÷  Ʃ freq_base) × 100',
    meta: '≥ 90%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'indicadoresExecucaoService.js (calcularIFM)',
  },
  {
    sigla: 'TEP',
    nome: 'Taxa de Evasão do Programa',
    dimensao: 'Execução do Programa',
    publicoOuFonte: 'Operação e cobertura',
    resultadoEsperado: 'Reduzir os desligamentos antecipados',
    definicaoOperacional: 'Percentual de participantes desligados antes da conclusão regular, excluídas as hipóteses que tecnicamente não caracterizem evasão',
    formula: '(Ʃ nº de evasões no período ÷ Ʃ nº total de participantes inseridos no período) × 100',
    meta: '≤ 15%',
    operador: '<=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'indicadoresExecucaoService.js (calcularTEP)',
  },
  {
    sigla: 'TRV',
    nome: 'Taxa de Reposição de Vagas',
    dimensao: 'Execução do Programa',
    publicoOuFonte: 'Operação e cobertura',
    resultadoEsperado: 'Preencher, durante a competência, as vagas ociosas na abertura do mês e as vagas efetivamente liberadas por desligamentos ocorridos no mês.',
    definicaoOperacional: 'Percentual de oportunidades de preenchimento efetivamente ocupadas por novas admissões durante o mês de referência. Vagas disponíveis = (5.000 − aprendizes ativos na abertura do mês) + todos os desligamentos efetivos que liberam vagas na competência (demissões, términos regulares e outras saídas definitivas). Excluir transferências internas que não liberem vagas. Incluir no numerador somente novas admissões efetivas na competência, sem contar transferências internas como admissão.',
    formula: 'TRV = [novas admissões efetivas no mês ÷ ((5.000 − aprendizes ativos na abertura do mês) + desligamentos efetivos que liberaram vagas no mês)] × 100. Se o denominador = 0: Não aplicável.',
    meta: '> 50%',
    operador: '>',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'indicadoresExecucaoService.js (calcularPVPeTRV)',
  },
  {
    sigla: 'IAG',
    nome: 'Índice de Abrangência Geográfica',
    dimensao: 'Execução do Programa',
    publicoOuFonte: 'Operação e cobertura',
    resultadoEsperado: 'Garantir a presença territorial do Programa nos 246 municípios do Estado',
    definicaoOperacional: 'Percentual de municípios com execução efetiva do Programa',
    formula: '(nº de municípios com pelo menos um aprendiz ativo ÷ 246) × 100',
    meta: '≥ 95%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'indicadoresExecucaoService.js (calcularIAG)',
  },
  {
    sigla: 'IRI',
    nome: 'Índice de Regularidade do Ingresso',
    dimensao: 'Verificação Inicial — 30 Dias',
    publicoOuFonte: 'Aprendiz',
    resultadoEsperado: 'Garantir a regularidade no Ingresso do Jovem no Programa',
    definicaoOperacional: 'Mede o grau de cumprimento das providências essenciais relacionadas à formalização e ao início da participação do jovem no Programa.\nConsidera a formalização contratual, registro do vínculo, acesso à conta para recebimento e participação na capacitação inicial.',
    formula: 'IRI = (nº de respostas positivas nas Q1–Q4 ÷ nº total de respostas válidas nas Q1–Q4) × 100',
    meta: '≥ 85%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'verificacao30DiasService.js',
  },
  {
    sigla: 'IRA',
    nome: 'Índice de Regularidade da Aprendizagem',
    dimensao: 'Verificação Inicial — 30 Dias',
    publicoOuFonte: 'Aprendiz',
    resultadoEsperado: 'Garantir a regularidade da aprendizagem',
    definicaoOperacional: 'Mede o grau de conformidade da execução inicial das atividades teóricas e práticas do Programa de Aprendizagem.\nConsidera a inserção na atividade prática, participação na formação teórica, cumprimento da jornada e compatibilidade com a frequência escolar.',
    formula: 'IRA = (nº de respostas positivas nas Q5–Q9 ÷ nº total de respostas válidas nas Q5–Q9) × 100',
    meta: '≥ 85%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'verificacao30DiasService.js',
  },
  {
    sigla: 'IEB',
    nome: 'Índice de Entregas e Benefícios',
    dimensao: 'Verificação Inicial — 30 Dias',
    publicoOuFonte: 'Aprendiz',
    resultadoEsperado: 'Garantir a entrega de material e benefícios',
    definicaoOperacional: 'Mede o percentual de cumprimento das entregas materiais e benefícios devidos ao aprendiz no período inicial de execução.\nConsidera o recebimento de uniforme, crachá, vale-transporte quando aplicável e remuneração quando já exigível.',
    formula: 'IEB = (nº de respostas positivas nas Q10, Q11, Q13 e Q19 ÷ nº total de respostas válidas aplicáveis nessas questões) × 100',
    meta: '≥ 85%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'verificacao30DiasService.js',
  },
  {
    sigla: 'IAA',
    nome: 'Índice de Acompanhamento do Aprendiz',
    dimensao: 'Verificação Inicial — 30 Dias',
    publicoOuFonte: 'Aprendiz',
    resultadoEsperado: 'Garantir o acompanhamento do Jovem Aprendiz',
    definicaoOperacional: 'Mede o grau de efetividade do acompanhamento e suporte disponibilizados ao jovem durante os primeiros 30 dias no Programa.\nConsidera a existência de orientação no local de prática, contato da entidade e conhecimento dos canais de atendimento e apoio.',
    formula: 'IAA = (nº de respostas positivas nas Q14, Q15, Q16 e Q20 ÷ nº total de respostas válidas nessas questões) × 100',
    meta: '≥ 85%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'verificacao30DiasService.js',
  },
  {
    sigla: 'IACA',
    nome: 'Índice de Adequação das Condições de Aprendizagem',
    dimensao: 'Verificação Inicial — 30 Dias',
    publicoOuFonte: 'Aprendiz',
    resultadoEsperado: 'Garantir regularidade nas condições de Trabalho do Jovem Aprendiz',
    definicaoOperacional: 'Mede o grau de conformidade das condições em que o jovem desenvolve suas atividades práticas com as regras do Programa.\nConsidera a compatibilidade das atividades executadas com a aprendizagem e a inexistência de exposição a atividades inadequadas, perigosas ou insalubres.',
    formula: 'IACA = (nº de respostas positivas nas Q17–Q18 ÷ nº total de respostas válidas nas Q17–Q18) × 100',
    meta: '≥ 85%',
    operador: '>=',
    unidade: 'Percentual',
    periodicidade: 'Mensal',
    motorCalculo: 'verificacao30DiasService.js',
  },
];

export const TOTAL_INDICADORES_CATALOGO = 44;
